Vagrant.configure("2") do |config|

  config.vm.define "rmqn1" do |node1|
    node1.vm.box = "bento/centos-8"
    node1.vm.hostname = "rmqn1"
    config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
    node1.vm.network "forwarded_port", guest: 15672, host: 8088
    node1.vm.provision "chef_solo" do |chef|
      chef.arguments = "--chef-license accept"
      chef.cookbooks_path = "../../cookbooks/linux"
      chef.roles_path = "../../roles"
      chef.add_role "rabbitmq"
    end
    node1.vm.provision "file", source: "../../scripts/rmq/rmq_cluster_bootstrap.sh", destination: "/tmp/rmq_cluster_bootstrap.sh"
  end

  config.vm.define "rmqn2" do |node2|
    node2.vm.box = "bento/centos-8"
    node2.vm.hostname = "rmqn2"
    config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"    
    node2.vm.provision "chef_solo" do |chef|
      chef.arguments = "--chef-license accept"
      chef.cookbooks_path = "../../cookbooks/linux"
      chef.roles_path = "../../roles"
      chef.add_role "rabbitmq"
    end  
    node2.vm.provision "file", source: "../../scripts/rmq/rmq_cluster_bootstrap.sh", destination: "/tmp/rmq_cluster_bootstrap.sh"
  end

  config.vm.define "rmqn3" do |node3|
    node3.vm.box = "bento/centos-8"
    node3.vm.hostname = "rmqn3"
    config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"    
    node3.vm.provision "chef_solo" do |chef|
      chef.arguments = "--chef-license accept"
      chef.cookbooks_path = "../../cookbooks/linux"
      chef.roles_path = "../../roles"
      chef.add_role "rabbitmq"
    end
    node3.vm.provision "file", source: "../../scripts/rmq/rmq_cluster_bootstrap.sh", destination: "/tmp/rmq_cluster_bootstrap.sh"
  end        

end
